# Generated by Django 4.2.16 on 2024-11-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Voter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voter_id_number", models.CharField(max_length=20)),
                ("first_name", models.TextField()),
                ("last_name", models.TextField()),
                ("street_number", models.TextField()),
                ("street_name", models.TextField()),
                ("apartment_number", models.TextField(blank=True, null=True)),
                ("zip_code", models.TextField()),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("date_of_registration", models.DateField(blank=True, null=True)),
                ("party_affiliation", models.TextField()),
                ("precinct_number", models.TextField()),
                ("v20state", models.BooleanField()),
                ("v21town", models.BooleanField()),
                ("v21primary", models.BooleanField()),
                ("v22general", models.BooleanField()),
                ("v23town", models.BooleanField()),
                ("voter_score", models.IntegerField()),
            ],
        ),
    ]
