# Generated by Django 4.2.16 on 2024-11-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("director", models.CharField(max_length=100)),
                ("genre", models.CharField(max_length=100)),
                ("release_year", models.IntegerField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="movie_images/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "movies",
                    models.ManyToManyField(related_name="tags", to="project.movie"),
                ),
            ],
        ),
    ]
