# Generated by Django 4.2.16 on 2024-11-21 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_alter_movie_director_alter_movie_release_year_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="movie", name="genre",),
    ]
